create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  visitor_id text,
  session_id text,
  event_name text not null,
  reading_id uuid,
  spread_type text,
  channel text,
  referrer text,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_date_name_idx
  on public.analytics_events(((created_at at time zone 'Asia/Shanghai')::date), event_name, created_at desc);

create index if not exists analytics_events_path_idx
  on public.analytics_events(((properties ->> 'path')));

create index if not exists analytics_events_session_idx
  on public.analytics_events(session_id, created_at desc);

create index if not exists analytics_events_user_idx
  on public.analytics_events(user_id, created_at desc)
  where user_id is not null;

alter table public.analytics_events enable row level security;

revoke all on public.analytics_events from anon, authenticated;
